/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details take a look at the 'Building Java & JVM projects' chapter in the Gradle
 * User Manual available at https://docs.gradle.org/7.5.1/userguide/building_java_projects.html
 */

plugins {
    application
    id("io.spring.dependency-management") version "1.0.13.RELEASE"
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

val piranhaVersion = "22.9.0"
val dataStreamVersion = "07.01.00-MS-GA"

java.sourceCompatibility = JavaVersion.VERSION_17

dependencies {
    implementation(enforcedPlatform("cloud.piranha:bom:${piranhaVersion}"))
    testImplementation("org.junit.jupiter:junit-jupiter:5.9.0")
    implementation("cloud.piranha:piranha-embedded:${piranhaVersion}")
    implementation("cloud.piranha.http:piranha-http-impl:${piranhaVersion}")
    implementation("cloud.piranha.http:piranha-http-webapp:${piranhaVersion}")
    implementation("one.microstream:microstream-storage-embedded:${dataStreamVersion}")
    implementation("org.apache.logging.log4j:log4j:2.19.0")
    implementation("org.apache.logging.log4j:log4j-core:2.19.0")
    implementation("org.apache.logging.log4j:log4j-slf4j2-impl:2.19.0")
    implementation("com.google.guava:guava:31.1-jre")

}

application {
    // Define the main class for the application.
    mainClass.set("com.example.App")
}

tasks.named<Test>("test") {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
}
