/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.example;

import cloud.piranha.embedded.*;
import cloud.piranha.http.impl.DefaultHttpServer;
import cloud.piranha.http.webapp.HttpWebApplicationServerProcessor;
import one.microstream.storage.embedded.types.EmbeddedStorage;
import one.microstream.storage.embedded.types.EmbeddedStorageManager;

import java.util.Date;

public class App {
    public static void main(String[] args) {

        final EmbeddedStorageManager storageManager = EmbeddedStorage.start();

// print the last loaded root instance,
// replace it with a current version and store it
        System.out.println(storageManager.root());
        storageManager.setRoot("Hello World! @ " + new Date());
        storageManager.storeRoot();

// shutdown storage
        storageManager.shutdown();
        EmbeddedPiranha piranha = new EmbeddedPiranhaBuilder()
                .servlet("HelloWorld", HelloWorldServlet.class)
                .servletMapping("HelloWorld", "/*")
                .buildAndStart();

        DefaultHttpServer server = new DefaultHttpServer(8080,
                new HttpWebApplicationServerProcessor(piranha), false);

        server.start();

    }
}
